# Generated by Django 5.1.6 on 2025-03-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('height', models.IntegerField(default=800)),
                ('width', models.IntegerField(default=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('spawn_pos', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('max_bullet', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeftWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('height', models.IntegerField(default=800)),
                ('width', models.IntegerField(default=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('height', models.IntegerField(default=800)),
                ('width', models.IntegerField(default=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('size', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shootgame.gun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
