# Generated by Django 5.1.4 on 2025-03-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shootgame", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bottom",
            new_name="GameArea",
        ),
        migrations.DeleteModel(
            name="LeftWall",
        ),
        migrations.DeleteModel(
            name="RightWall",
        ),
    ]
