# Generated by Django 5.1.4 on 2025-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shootgame", "0002_rename_bottom_gamearea_delete_leftwall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamearea",
            name="point_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gamearea",
            name="point_y",
            field=models.IntegerField(default=0),
        ),
    ]
